name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  testing:
    name: Dummy test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: 'current-major'
          - profile: 'next-major'
    steps:
      - name: Custom action
        uses: lal65/drupal-module-qa-action@main
        with:
          profile: ${{ matrix.profile }}
